GET http://localhost:8080

### local signup

POST http://localhost:8080/auth/signup
Content-Type:  application/json; charset=utf-8

{
    "nick": "adsfadsfasfd",
    "email": "test@test2.com",
    "password": "12341234"
}

### local login

POST http://localhost:8080/auth/login
Content-Type: application/json;charset=utf-8

{
  "email": "test100@test100.com",
  "password": "123123123"
}

### local logout


POST http://localhost:8080/auth/logout
Content-Type:  application/json; charset=utf-8

### getPost

GET http://localhost:8080/post


### hashtags
GET http://localhost:8080/post/hashtag?hashtag=hello-world!!